version: "3.8"
services:
  database:
    image: postgres
    container_name: dbt-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../dataset:/tmp/dataset
      - ../sql/create_and_fill_tables.sql:/docker-entrypoint-initdb.d/create_and_fill_tables.sql
  dbt:
    image: dbt
    container_name: dbt
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ${LOCAL_DBT_PATH}:/root/dbt/
